### ISSUE TITLE
Compatibilidade com Retorno Caixa Sigcb e Sicob

### ISSUE THREAD

**Issue by andersondanilo** [andersondanilo/cnab_yaml#7]
Atualmente usamos o código bancário e o layout para identificar o formato, porém parece que a caixa tem 2 formatos no mesmo layout 400bytes.

**Comment by juliolustosa** [comment]
Acredito que este Pull Request venha a resolver.
https://github.com/andersondanilo/cnab_yaml/pull/9

**Comment by andersondanilo** [comment]
Merge efetuado

**Comment by juliolustosa** [comment]
Obrigado, precisando pode contar comigo.
Abraços.
